language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install numpy
  - pip install scipy
  - pip install PySide2 pytest-qt pytest-cov pytest-mock
# command to run tests
script:
  - python -m pytest -vv --cov PIM_Calculator
