language: python
services: xvfb
python:
  - "3.6"
  - "3.9"
# command to install dependencies
install:
  - pip install numpy
  - pip install scipy
  - pip install PySide2==5.15.2 pytest-qt==3.3.0 pytest-cov pytest-mock==3.5.1 matplotlib pytest-xvfb==2.0.0
# command to run tests
script:
  - cd python && python -m pytest -vv --cov ./PIM_Calculator
