language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install numpy
  - pip install scipy
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
